### ISSUE TITLE
error importing

### ISSUE THREAD

**Issue by bousalman** [corelan/mona#15]
Hi there,
I am trying to use the mona.py module with Immunity debugger v1.85 but I get error message "pycommands: error importing module."
already did place mona.py file inside the pycommands folder.

Regards,

**Comment by corelanc0d3r** [comment]
are you running immunity with admin permissions ?
does mona.py contain the actual python code ?

also, if you have downloaded mona.py and placed it in the folder, you may have to change the file properties and mark it as safe

**Comment by bousalman** [comment]
thanks Sir
turns out that the python file in covered with HTML.
I had to copy it properly 
Regards.
