### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getBaseAddress'

### ISSUE THREAD

**Issue by junmoxiao** [corelan/mona#17]
Once i execute a command,it'l give me this information.
My OS is window 7 64bit.
I install 32bit windbg and 64bit windbg both.
The 32bit windbg can execute the mona plugin success ,but the 64bit windbg will give me this  information:

> 0:000> !py mona modules
> Hold on...
> [+] Command used:
> !py mona.py modules
> 
> ---------- Mona command started on 2016-12-13 01:39:34 (v2.0, rev 567) ----------
> [+] Processing arguments and criteria
>     - Pointer access level : X
> [+] Generating module info table, hang on...
>     - Processing modules
> ** Error trying to process module api_ms_win_crt_locale_l1_1_0
> ** Error trying to process module api_ms_win_core_processthreads_l1_1_1
> ** Error trying to process module api_ms_win_crt_convert_l1_1_0
> ** Error trying to process module api_ms_win_crt_stdio_l1_1_0
> ** Error trying to process module ConsoleApplication5
> ** Error trying to process module kernel32
> ** Error trying to process module api_ms_win_core_localization_l1_2_0
> ** Error trying to process module api_ms_win_core_file_l2_1_0
> ** Error trying to process module ntdll
> ** Error trying to process module api_ms_win_core_timezone_l1_1_0
> ** Error trying to process module ucrtbase
> ** Error trying to process module api_ms_win_crt_heap_l1_1_0
> ** Error trying to process module api_ms_win_core_synch_l1_2_0
> ** Error trying to process module KERNELBASE
> ** Error trying to process module VCRUNTIME140
> ** Error trying to process module api_ms_win_core_file_l1_2_0
> ** Error trying to process module api_ms_win_crt_string_l1_1_0
> ** Error trying to process module api_ms_win_crt_runtime_l1_1_0
> ** Error trying to process module api_ms_win_crt_math_l1_1_0
> ** Error trying to process module api-ms-win-core-synch-l1-2-0.dll
> ********************************************************************************
> Traceback (most recent call last):
>   File "mona.py", line 18183, in main
>     commands[command].parseProc(opts)
>   File "mona.py", line 11240, in procShowMODULES
>     modulestosearch = getModulesToQuery(modulecriteria)
>   File "mona.py", line 5442, in getModulesToQuery
>     populateModuleInfo()
>   File "mona.py", line 5557, in populateModuleInfo
>     thismod = MnModule(key)
>   File "mona.py", line 2538, in __init__
>     mzbase    = mod.getBaseAddress()
> AttributeError: 'NoneType' object has no attribute 'getBaseAddress'
> 
> ********************************************************************************
> 

and every command can't be execute yet

> 0:000> !py mona rop
> Hold on...
> [+] Command used:
> !py mona.py rop
> 
> ---------- Mona command started on 2016-12-13 01:45:00 (v2.0, rev 567) ----------
> [+] Processing arguments and criteria
>     - Pointer access level : X
> [+] Generating module info table, hang on...
>     - Processing modules
> ** Error trying to process module api_ms_win_crt_locale_l1_1_0
> ** Error trying to process module api_ms_win_core_processthreads_l1_1_1
> ** Error trying to process module api_ms_win_crt_convert_l1_1_0
> ** Error trying to process module api_ms_win_crt_stdio_l1_1_0
> ** Error trying to process module ConsoleApplication5
> ** Error trying to process module kernel32
> ** Error trying to process module api_ms_win_core_localization_l1_2_0
> ** Error trying to process module api_ms_win_core_file_l2_1_0
> ** Error trying to process module ntdll
> ** Error trying to process module api_ms_win_core_timezone_l1_1_0
> ** Error trying to process module ucrtbase
> ** Error trying to process module api_ms_win_crt_heap_l1_1_0
> ** Error trying to process module api_ms_win_core_synch_l1_2_0
> ** Error trying to process module KERNELBASE
> ** Error trying to process module VCRUNTIME140
> ** Error trying to process module api_ms_win_core_file_l1_2_0
> ** Error trying to process module api_ms_win_crt_string_l1_1_0
> ** Error trying to process module api_ms_win_crt_runtime_l1_1_0
> ** Error trying to process module api_ms_win_crt_math_l1_1_0
> ** Error trying to process module api-ms-win-core-synch-l1-2-0.dll
> ********************************************************************************
> Traceback (most recent call last):
>   File "mona.py", line 18183, in main
>     commands[command].parseProc(opts)
>   File "mona.py", line 11341, in procROP
>     findROPGADGETS(modulecriteria,criteria,endings,maxoffset,depth,split,thedistance,fast,mode)
>   File "mona.py", line 6033, in findROPGADGETS
>     modulestosearch = getModulesToQuery(modulecriteria)
>   File "mona.py", line 5442, in getModulesToQuery
>     populateModuleInfo()
>   File "mona.py", line 5557, in populateModuleInfo
>     thismod = MnModule(key)
>   File "mona.py", line 2538, in __init__
>     mzbase    = mod.getBaseAddress()
> AttributeError: 'NoneType' object has no attribute 'getBaseAddress'
> 
> ********************************************************************************
>

**Comment by corelanc0d3r** [comment]
Hi

64bit is not supported by mona.py - it expects 32bit addresses etc, so I'm pretty sure it won't work.

**Comment by junmoxiao** [comment]
i know.thank you

**Comment by junmoxiao** [comment]
I read this link http://expdev-kiuhnm.rhcloud.com/2015/05/19/mona-2/
