### ISSUE TITLE
In Immunity debugger lower-case disassembly breaks multiple !mona commands

### ISSUE THREAD

**Issue by tanelikaivola** [corelan/mona#18]
If "Debugging options -> Disasm -> Disassemble in lowercase" is enabled, !mona rop produces invalid results. !mona stackpivot doesn't produce any results.

Suggestions how to fix this (pick one):
1. Uppercase the disassembly / lowercase find patterns / do whatever needed to make them match
1. Make !mona commands whine verbosely if disassembly is in lower-case
1. For the duration of !mona commands, configure Immunity debugger to produce disassembly in upper-case
1. Document this somehow =D

**Comment by corelanc0d3r** [comment]
probably needs more testing, but commit https://github.com/corelan/mona/commit/9f1c32bc13823c11c3eb64ffba02152754ec78a0 should fix the issue :)
