### ISSUE TITLE
Error while searching for pointers

### ISSUE THREAD

**Issue by dmitriy-ddr** [corelan/mona#22]
The plug-in was installed in accordance with the https://github.com/corelan/windbglib
I tried different versions of this plugin, including the last one
I assume that this error has been discussed many times, but I have not found solutions to this problem

0:000> !py mona jmp -r ESP
Hold on...
[+] Command used:
!py mona.py jmp -r ESP
---------- Mona command started on 2017-10-15 04:41:48 (v2.0, rev 570) ----------
[+] Processing arguments and criteria
    - Pointer access level : X
[+] Generating module info table, hang on...
    - Processing modules
********************************************************************************
Traceback (most recent call last):
  File "mona.py", line 18207, in main
    commands[command].parseProc(opts)
  File "mona.py", line 11212, in procFindJMP
    all_opcodes=findJMP(modulecriteria,criteria,args["r"].lower().strip())
  File "mona.py", line 5846, in findJMP
    modulestosearch = getModulesToQuery(modulecriteria)
  File "mona.py", line 5466, in getModulesToQuery
    populateModuleInfo()
  File "mona.py", line 5577, in populateModuleInfo
    allmodules=dbg.getAllModules()
  File "C:\dbgs\WinDbg\windbglib.py", line 1160, in getAllModules
    getModulesFromPEB()
  File "C:\dbgs\WinDbg\windbglib.py", line 366, in getModulesFromPEB
    moduleLst = pykd.typedVarList(peb.Ldr.deref().InLoadOrderModuleList, "ntdll!_LDR_DATA_TABLE_ENTRY", "InMemoryOrderLinks.Flink")
TypeException: _LDR_DATA_TABLE_ENTRY : symbol name is not found

********************************************************************************

**Comment by corelanc0d3r** [comment]
Hi,

as far as I can tell, it looks like your WinDBG instance doesn't have symbols set up yet.

**Comment by dmitriy-ddr** [comment]
yes, this is the fault of my fault, associated with the symbols. Now there are warnings, but they do not seem to affect the operation of the extension. thanks for the feedback

*** ERROR: Module load completed but symbols could not be loaded for image00400000
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\WINDOWS\system32\msvcrt.dll - 
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\WINDOWS\system32\kernel32.dll -

**Comment by corelanc0d3r** [comment]
cool, thanks for confirming

the remaining "errors" are windbg errors, and won't affect mona.py

thanks !
