### ISSUE TITLE
x64dbg support 

### ISSUE THREAD

**Issue by wangray** [corelan/mona#23]
Work in progress: https://github.com/wangray/mona

How likely is this to get merged? Should we maintain x64dbg support separately? @corelanc0d3r

**Comment by corelanc0d3r** [comment]
it is quite likely to be merged, however the changes you are making should not break support for mona under immunity nor windbg.
Furthermore, any functional changes (changes to the way mona works today) will require some further discussion.
To keep things manageable, please only submit PRs with smaller changes.
Finally, I would appreciate some basic testing in immunity/windbg (as I may not have time to test everything on a short term, thus slowing down the process)

thanks !

Peter

**Comment by corelanc0d3r** [comment]
I'm closing this case, but of course I look forward to seeing your PRs :)
