### ISSUE TITLE
error importing module mona at Immunity Debugger

### ISSUE THREAD

**Issue by ka223** [corelan/mona#27]
### Expected behavior 
Possible to use the mona plugin in immuniy debugger 1.85.

### Actual behavior
!mona
PyCommands: error importing module

### Steps to reproduce the problem
add mona.py to the PyCommands folder
start Immunity Debugger
use !mona

### Other useful information
OS: Windows xp
immuniy debugger 1.85

**Comment by ka223** [comment]
ok, I found the issue
https://github.com/corelan/mona/issues/15

**Comment by Dagwal** [comment]
drop [Mona.py](https://github.com/corelan/mona/blob/master/mona.py) into the 'PyCommands' folder (inside the Immunity Debugger application folder).
