### ISSUE TITLE
Failed to Import Module

### ISSUE THREAD

**Issue by snoski3** [corelan/mona#29]
When opening a new issue, please fill out the following sections:

### Expected behavior 
List the modules that don't have any memory checks
### Actual behavior
![image](https://user-images.githubusercontent.com/5173575/47048258-7f248c00-d15f-11e8-9410-6fe93196fb06.png)

### Steps to reproduce the problem
Type !mona modules

### Other useful information (mona version, debugger & debugger version, OS version, etc)
mona "current version" as of 10/16/2018, immunity debugger version 1.85, python 2.7.15, windows 10 64 current version

**Comment by corelanc0d3r** [comment]
Hi

I assume that none of the mona commands will work, as it looks like Immunity doesn't recognize mona.py.
Can you confirm that mona.py is in the correct folder and contains the actual python code?
Also, after downloading the file from github and storing it inside the Immunity folder, did you check the properties of the file and "unprotect" it?

**Comment by corelanc0d3r** [comment]
I'll close this issue, but please don't hesitate to reopen if needed
