### ISSUE TITLE
crach at command "mona rop -m ntdll"

### ISSUE THREAD

**Issue by meirl-zz** [corelan/mona#30]
Crash when I run the command: !mona rop -m ntdll

### Steps to reproduce the problem
Included exe file and log files:
![Capture](https://user-images.githubusercontent.com/7955617/57486025-d6ce4480-72b5-11e9-8bc5-0202bbcd2b69.PNG)
[_rop_progress_for_testing.exe_1792.log](https://github.com/corelan/mona/files/3163968/_rop_progress_for_testing.exe_1792.log)
[Log.txt](https://github.com/corelan/mona/files/3163969/Log.txt)
[for_testing_exe_.txt](https://github.com/corelan/mona/files/3163971/for_testing_exe_.txt)
Windows 7 SP1 syswow64 folder: [ntdll_dll_.txt](https://github.com/corelan/mona/files/3163973/ntdll_dll_.txt)

### Other useful information
Windows 7 x64 on vmware workstation
**4 GB RAM for the VM!**
**I am running Immunity debugger as administrator**
Installed visual studio 2017 c++ redistributable x32
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
Immunity debugger 1.85
Mona Plugin version : 2.0 r585 (latest update)

**Comment by corelanc0d3r** [comment]
Hi, in order for me to be able to reproduce the issue, would it be possible to send me the actual application (source code) so I can try it on my own machine?
thanks

**Comment by meirl-zz** [comment]
source code:
compiled in VS 2017.

```
#include <stdio.h>
void main()
{
	printf("hello world!");
}
```

But this crash happens with any exe in the VM when I run  !mona rop -m ntdll

The problem is in ntdll with the version of my VM.
I included in the bug report the ntdll file from my VM so you can try to rename in, load in manually to any process and see if running   !mona rop -m <module name> will crash

If you want I can give you remote access to my VM, or I can maybe upload the VM and send you a link, but it is 20 GB

**Comment by corelanc0d3r** [comment]
I was able to reproduce the issue - it looks like an unhandled exception in one of the immunity libraries.  I can't fix the issue, but I have added some exception handling around the use of it. please try again with the latest version of mona (r587 or up)

**Comment by meirl-zz** [comment]
Works great! Thanks
