### ISSUE TITLE
!mona modules got nothing in Immunity Debugger

### ISSUE THREAD

**Issue by sinbargit** [corelan/mona#35]
I put the mona.py into Immunity Debugger's PyCommands. And type "`!mona modules`" there 0 line of results. The screenshot at below:

<img width="788" alt="屏幕快照 2019-05-29 下午6 27 36" src="https://user-images.githubusercontent.com/16011848/58550071-92442200-823f-11e9-8476-9a4772f1fe11.png">
Does that right?
I do the test on both windows7 and windowsXp and got the same result.

**Comment by corelanc0d3r** [comment]
is immunity connected to a process?

**Comment by corelanc0d3r** [comment]
also, I see that you're running mona version 565 - that's an old version. please run !mona up  to get the latest version

**Comment by sinbargit** [comment]
@corelanc0d3r  Thanks, My mistake, it is not connected to a process.
