### ISSUE TITLE
Invalid opcode when searching for possible gadgets

### ISSUE THREAD

**Issue by cwaazywabbit** [corelan/mona#39]
Checking RM2MP3Converter on Win 7 Ultimate x64, an invalid opcode was returnd in rop.txt

### Expected behavior 
```
0x100150xx :  # PUSH EAX # ADD DWORD PTR DS:[EAX],EDX # MOV EAX,1 # RETN    ** [MSRMfilter03.dll] **   |   {PAGE_EXECUTE_READ}
```

### Actual behavior
```
0x100150xx :  # LEA EDX,ESP # PUSH EAX # ADD DWORD PTR DS:[EAX],EDX # MOV EAX,1 # RETN    ** [MSRMfilter03.dll] **   |   {PAGE_EXECUTE_READ}
```

as can be seen, `LEA EDX,ESP` has been suggested, which is an invalid opcode, AFAIK.

**Comment by corelanc0d3r** [comment]
hi - do you mean that LEA EDX,ESP is not a valid instruction?  Or do you mean it won't work under the context of your application?
Mona.py only checks if the debugger recognizes/translates opcode into an instruction, it doesn't check if the instruction is valid/meaningful

**Comment by cwaazywabbit** [comment]
Hi Peter,
LEA's mnemonics does not contain the syntax LEA reg,reg (http://faydoc.tripod.com/cpu/lea.htm)
the debugger cannot/should not recognize it as a possible instruction because it cannot be.
Test it yourself (for example here: https://defuse.ca/online-x86-assembler.htm)

**Comment by corelanc0d3r** [comment]
Hi Shadi, I fully understand, but I am relying on Immunity's (and WinDBG's) ability to do the translation, and I'm trying to avoid that I have to start checking syntax in mona. That would be cumbersome and would affect performance...   Does WinDBG also present the same asm instruction when you look at the same location?  Or is this an immunity issue?

thanks !

**Comment by corelanc0d3r** [comment]
hi @cwaazywabbit - can you please test if this is an immunity issue, or does it also happen on windbg?

**Comment by corelanc0d3r** [comment]
closed the issue due to lack of activity. feel free to reopen if needed
