### ISSUE TITLE
Error while creating a ROP gadget

### ISSUE THREAD

**Issue by SlidingWindow** [corelan/mona#42]
When opening a new issue, please fill out the following sections:

### Expected behavior 

Mona.py should create rop_chains.txt and rop.txt files after running one of the following commands:

!mona rop -m slmfc.dll -n -cpb "\x00\x0a\x0d"
!mona rop -m slmfc.dll -n cpb "\x00\x0a\x0d"
!mona rop -m *.dlll -n cpb "\x00\x0a\x0d"
!mona rop -m *.dlll -n -cpb "\x00\x0a\x0d"
!mona rop
!mona rop -m slmfc.dll

### Actual behavior
Mona throws an 
[_rop_progress_SLmail.exe_1164.log](https://github.com/corelan/mona/files/3816214/_rop_progress_SLmail.exe_1164.log)
error (see screenshot). 

I  see local variable referenced before assignment error on a splash screen ( could not capture that error though)

### Steps to reproduce the problem
1. Install SLMail 5.5.x on Windows 7 SP1
2. Make sure that DEP is set to OptOut mode ( not sure if that matters)

### Other useful information (mona version, debugger & debugger version, OS version, etc)
1. Mona version: latest version as of today
2. Python version 2.7.16
3. Immunity Debugger version 1.85
4. O.S : Windows 7 SP1
<img width="1426" alt="Screenshot 2019-11-06 at 10 32 07 PM" src="https://user-images.githubusercontent.com/22855648/68328179-39c75980-00e8-11ea-8134-6967839f8f00.png">

**Comment by SlidingWindow** [comment]
I see this error:

`0BADF00D       - Filtering and mutating 8258 gadgets
0BADF00D         - Progress update : 1000 / 8258 items processed (Thu 2019/11/07 09:47:24 AM) - (12%)
0BADF00D         - Progress update : 2000 / 8258 items processed (Thu 2019/11/07 09:47:28 AM) - (24%)
0BADF00D         - Progress update : 3000 / 8258 items processed (Thu 2019/11/07 09:47:32 AM) - (36%)
0BADF00D         - Progress update : 4000 / 8258 items processed (Thu 2019/11/07 09:47:35 AM) - (48%)
0BADF00D         - Progress update : 5000 / 8258 items processed (Thu 2019/11/07 09:47:39 AM) - (60%)
0BADF00D         - Progress update : 6000 / 8258 items processed (Thu 2019/11/07 09:47:43 AM) - (72%)
0BADF00D         - Progress update : 7000 / 8258 items processed (Thu 2019/11/07 09:47:47 AM) - (84%)
0BADF00D         - Progress update : 8000 / 8258 items processed (Thu 2019/11/07 09:47:51 AM) - (96%)
0BADF00D         - Progress update : 8258 / 8258 items processed (Thu 2019/11/07 09:47:51 AM) - (100%)
0BADF00D   [+] Creating suggestions list
0BADF00D   [+] Processing suggestions
0BADF00D   [+] Launching ROP generator
0BADF00D   [+] Attempting to produce rop chain for VirtualProtect
0BADF00D       Thu 2019/11/07 09:47:57 AM: Step 1/7: esi
0BADF00D       Thu 2019/11/07 09:47:57 AM: Step 2/7: ebp
0BADF00D   ********************************************************************************
           Traceback (most recent call last):
             File "C:\Program Files\Immunity Inc\Immunity Debugger\PyCommands\mona.py", line 18681, in main
               commands[command].parseProc(opts)
             File "C:\Program Files\Immunity Inc\Immunity Debugger\PyCommands\mona.py", line 11683, in procROP
               findROPGADGETS(modulecriteria,criteria,endings,maxoffset,depth,split,thedistance,fast,mode,sortedprint)
             File "C:\Program Files\Immunity Inc\Immunity Debugger\PyCommands\mona.py", line 6534, in findROPGADGETS
               vplogtxt = createRopChains(suggestions,interestinggadgets,ropgadgets,modulecriteria,criteria,objprogressfile,progressfile)
             File "C:\Program Files\Immunity Inc\Immunity Debugger\PyCommands\mona.py", line 8523, in createRopChains
               thischain[thisreg] = putValueInReg(thisreg,jmpptr,"& " + jmptype + " [" + jmpinfo + "]" + jmpmodinfo,suggestions,interestinggadgets,criteria)
           UnboundLocalError: local variable 'jmpmodinfo' referenced before assignment

0BADF00D   ********************************************************************************
75D8845D   [09:48:13] Debug string: Forced: 0`

It says the local variable jmpmodinfo is referenced before assignment but I see that it is indeed assigned before being referenced:

`else:
                        jmpinfo = MnPointer(jmpptr).belongsTo()
                        tmod = MnModule(jmpinfo)
                        jmpmodinfo = getGadgetAddressInfo(jmpptr)
                    thischain[thisreg] = putValueInReg(thisreg, jmpptr,
                                                       "& " + jmptype + " [" + jmpinfo + "]" + jmpmodinfo, suggestions,
                                                       interestinggadgets, criteria) `

**Comment by corelanc0d3r** [comment]
can you please try the very latest version and see if the issue has been resolved? thanks !

**Comment by SlidingWindow** [comment]
It works! Thanks a ton!

**Comment by corelanc0d3r** [comment]
Great, thanks for testing & confirming!
