### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by oxr463** [corelan/mona#46]
When opening a new issue, please fill out the following sections:

### Expected behavior 

Typically, a README.md file contains a summary of what the project is/does, and also contains references to further documentation.

### Actual behavior

There is no documentation found in this repository.

### Steps to reproduce the problem

Check the README.md file for any documentation or references.

### Other useful information (mona version, debugger & debugger version, OS version, etc)

N/A

**Comment by corelanc0d3r** [comment]
updated README.md file
