### ISSUE TITLE
Add Python2.7 shebang

### ISSUE THREAD

**Issue by goncalor** [corelan/mona#48]
### Expected behavior 
The script should run without crashing even if a system uses Python3 as default.

### Actual behavior
The script crashes when loaded with Python3, the current supported version which is becoming more standard.

### Steps to reproduce the problem
`python mona.py` on a system for which Python3 is default.

I suggest adding the following shebang to `mona.py`.
`#!/usr/bin/env python2.7`

As an example, trying to load Mona from Immunity Debugger on a Windows system with Python3 as default will result in an error. By adding that shebang, Mona loads fine if the system also has Python2.7 installed.

**Comment by corelanc0d3r** [comment]
add the line, please confirm it works as intended now, thanks !

**Comment by goncalor** [comment]
Yup, it works. Thanks!
