### ISSUE TITLE
'compare' does not search file in workingfolder

### ISSUE THREAD

**Issue by stloewen** [corelan/mona#51]
### Expected behavior 
With a custom workingfolder configured, when using `!mona compare -a ESP -f bytearray.bin` the file `bytearray.bin` should be found in the workingfolder.

### Actual behavior
`Unable to find/read file bytearray.bin`

### Steps to reproduce the problem
```
!mona config -set workingfolder C:\immdbg\%p
!mona bytearray
!mona compare -a ESP -f bytearray.bin
```

**Comment by corelanc0d3r** [comment]
HI @stloewen - unfortunately that is the way `mona.py` was designed.
The `workingfolder` option only applies to "output" files generated by `mona.py` (so you can control where they get written to).
For "input" files, you'll have to specify the full path.

**Comment by stloewen** [comment]
Then the name outputfolder would be more fitting I'd say. 

Would you be willing to implement my suggested change, or accept a pull request (if I find the time)? Or are you not interested in changing the behavior?

**Comment by corelanc0d3r** [comment]
> Then the name outputfolder would be more fitting I'd say.

True

> Would you be willing to implement my suggested change, or accept a pull request (if I find the time)? Or are you not interested in changing the behavior?

I do accept Pull Requests, we can change the default behaviour indeed, but we'll have to make the change for all functions that take files as input.

Woudl this meet your requirements:

- If no absolute path is specified , then the file should be located in the "workingfolder"
- If no workingfolder is specified, take the default workingfolder
- If an absolute path is specified, read the file from the absolute path
- If a relative path is specified, consider it to be relative from the "workinfolder" (custom folder, or default as fall back)
-
