### ISSUE TITLE
pycommands: error importing module

### ISSUE THREAD

**Issue by zaklahunik** [corelan/mona#55]
When opening a new issue, please fill out the following sections:

### Actual behavior
pycommands: error importing module
### Steps to reproduce the problem
Windows 10 Home Native (no VM)
Immunity debugger using command !mona 

### Other useful information (mona version, debugger & debugger version, OS version, etc)
Python 2.7 32-bit
PATH added 
Other commands working like !list or !heap or !mike

I can see when I run any other command a .pyc file is created but that never happens when trying to use mona commands. 

I verified the size of mona.py file and privileges. It keeps showing  "pycommands: error importing module"
Please help

**Comment by corelanc0d3r** [comment]
hard to tell what went wrong, but can you please verify that the file contains python code and not html?

**Comment by zaklahunik** [comment]
Yes the file contained python. I found the problem after a week of research. Turns out I had python 2.7.17 and I needed to downgrade to 2.7.10
