### ISSUE TITLE
jmp esp error Windows XP

### ISSUE THREAD

**Issue by dhaneshsivasamy07** [corelan/mona#60]
### Expected behavior 
- Mona should provide the output of the instruction `jmp esp` upon executing `!mona jmp -r esp`

### Actual behavior
- Mona errors out, like below
![image](https://user-images.githubusercontent.com/55705969/198092567-a387eb68-0b4f-4e38-a7c4-c2eb5302499c.png)

### Steps to reproduce the problem
- Open Immunity debugger and load mona.py 
- Search for jmp esp instruction with `!mona jmp -r esp`  command and observe the output

### Other useful information (mona version, debugger & debugger version, OS version, etc)
- Windows Version: XP
- Immunity Debugger Version: 1.85
- Mona Version: Latest Patch
- Python Version: 2.7.18
- Other mona commands work, `!mona find -s '\xff\xe4'` this works fine

**Comment by dhaneshsivasamy07** [comment]
![image](https://user-images.githubusercontent.com/55705969/198094752-51832b16-6eb1-4f8e-9322-0727d8d8cbb3.png)

Log from immunity debugger

**Comment by corelanc0d3r** [comment]
hi, thanks for reporting - can you please run !mona up and try again with the latest version?
(revision 618 or higher)

thanks

**Comment by dhaneshsivasamy07** [comment]
Hi @corelanc0d3r, this was the output of the command `!mona up`. As you can see from the cmd on the right my machine has internet access too. Thank you
![image](https://user-images.githubusercontent.com/55705969/198300157-d4b4b195-cd4f-446d-a8b6-e65f904da42b.png)

**Comment by dhaneshsivasamy07** [comment]
Sorry I didn't check the last commit, once I loaded with the updated script I was able to obtain the jmp esp address. But still the update fails, can you please help me with this? Thank you

![image](https://user-images.githubusercontent.com/55705969/198301281-7a711b67-819c-4823-9af5-a262309da2a6.png)

**Comment by corelanc0d3r** [comment]
you're running an outdated version of python. Install a more recent version (2.7.14 or higher) to fix the update problem.

**Comment by dhaneshsivasamy07** [comment]
Hi @corelanc0d3r , I previously used Python 2.7.18 and now I downgraded it to 2.7.15 still the error message prevails,
I have also included the output of the command `python --version` and to check the internet connectivity, I pinged google.com

![image](https://user-images.githubusercontent.com/55705969/198498798-101b401e-dfd3-4105-9089-526fc08b7386.png)

**Comment by corelanc0d3r** [comment]
perhaps windows XP does not support modern crypto/HTTPS connections, causing the update process to fail.
I don't think this is a mona problem, I'm closing the issue  :)

**Comment by dhaneshsivasamy07** [comment]
Thank you for the help @corelanc0d3r :)

**Comment by dhaneshsivasamy07** [comment]
Hi @corelanc0d3r, Indeed, its the problem with python in xp

> perhaps windows XP does not support modern crypto/HTTPS connections, causing the update process to fail. I don't think this is a mona problem, I'm closing the issue :)

- Found  a work around for this,

> python -m pip install urllib3 certifi

- Add the following in the mona.py file

```python
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

# add the following in line 13499
u = urllib.urlretrieve(updateurl, context=ctx)
```
- Line to be updated [here](https://github.com/corelan/mona/blob/6cad24fc30020f96a883c17a3d3763639656fa01/mona.py#L13499)

**Comment by corelanc0d3r** [comment]
understood - unfortunately I am not able to rely on module updates or the use of non-standard modules... but you're right, that would be a workaround indeed
